### ISSUE TITLE
Cross join 

### ISSUE THREAD

**Issue by geoHeil** [harsha2010/magellan#102]
Will magellan resort to a cross join for the intersection operation?
Or will an intelligent index I.e. Rtree be used?

**Comment by harsha2010** [comment]
what is your performance requirement? with certain spark sql optimizations that magellan uses, you can cross join several billion rows in a couple of minutes. I am working on support for spatial indexes (the master branch already has some support but more work is needed). what is your use case? how big of a dataset are you trying to join?

**Comment by geoHeil** [comment]
I am trying to join polygons with points and polygons with polygons. So far
the cross join by hive esri udf blew up pretty quickly. What are the
optimizations of magellan if you don't build an index?
Ram Sriharsha <notifications@github.com> schrieb am Do. 9. März 2017 um
21:34:

**Comment by harsha2010** [comment]
how many points are there and how many polygons are there in the join?

**Comment by geoHeil** [comment]
Should be several million points and up to a million polygons.
Ram Sriharsha <notifications@github.com> schrieb am Do. 9. März 2017 um
22:53:

**Comment by geoHeil** [comment]
A point or polygon can intersecti with 0,1, or multiple polygons. I want to
know for each point which are the intersecting/ containing polygons.
Georg Heiler <georg.kf.heiler@gmail.com> schrieb am Do. 9. März 2017 um
22:57:

**Comment by harsha2010** [comment]
yeah, if you have a million polygons then it might be more challenging...as long as the # of polygons is less than a few thousand and fit into memory, we do use broadcast joins, and unlike ESRI Hive, you don't end up with serialization and UDF overheads which are very high due to virtual function calls... 
but with a million polygons we won't be using broadcasting so you will default to cross join even in Magellan today. I'm working on a spatial join which should be ready in a few weeks...most of the code is already on master but right now you'll have to hand write the join.. I'm working on automating this. Will let you know once it is ready

**Comment by geoHeil** [comment]
Sounds great did you have a look at the implementation of geo spark? They
seem to use some neat R and STR trees.
Ram Sriharsha <notifications@github.com> schrieb am Do. 9. März 2017 um
23:07:

**Comment by stevebuckingham** [comment]
Look forward to the SpatialJoin at the moment I've got it running with a BroadcastNestedLoop to to a within join between a point and some polygons. But it is taking about 2 hours on a reasonable size cluster in AWS to join and output to parquet 66,000 polygons and 200,000,000 points.

**Comment by kanghq** [comment]
Hi, any update for the indexing?
and if not would you mind introducing how to utilize the indexing manually?

**Comment by geoHeil** [comment]
@harsha2010 any news about an update regarding the spatial join?

**Comment by harsha2010** [comment]
this has been done in #122 
Please give it a try and let me know how it works for you
