### ISSUE TITLE
Upgrade to Spark 1.5

### ISSUE THREAD

**Issue by harsha2010** [harsha2010/magellan#18]
Spark 1.5 adds a null safe eval and codegen methods to Expressions, and also turns codegen on by default.
Currently these are breaking changes at runtime that don't allow Magellan compiled on Spark 1.4 to run on Spark Master. When Spark 1.5 comes out, we need to upgrade Magellan so that it can run on Spark 1.5.

**Comment by JoshRosen** [comment]
Is it important that Magellan continues to support Spark 1.4 or is the plan to only be compatible with 1.5+? I would be glad to help with this update, but I imagine that things may be somewhat more complicated if compatibility with older Spark versions is a concern.

**Comment by harsha2010** [comment]
Yes we definitely need backward compatibility... For now I am ok with abandoning 1.4 support but very soon we'll need to stabilize the spark APIs enough so we can support multiple versions. Let's chat more next week

**Comment by JoshRosen** [comment]
There are definitely libraries which are compatible with a range of Spark versions (such as `spark-redshift`). It was only Magellan's use of a few internal Spark APIs that had me worried.

From my work on `spark-redshift`, I came up with a neat way to be able to build against a single Spark and Hadoop configuration and then test those artifacts against different Hadoop and Spark versions at runtime. This should help in gaining confidence that the published release artifacts will work across all supported versions.

I'm going to submit a PR shortly to port this SBT and Travis logic over to this project. I'll tell Travis to run the 1.5.x configurations but to ignore their results for now. This will be able to give us a barometer on how close we are to full cross-version support without breaking the build while we're still working out any issues.

**Comment by JoshRosen** [comment]
I spent a bit of time this evening trying to see if I could come up with a way to modify Magellan so that we could compile against Spark 1.4.1 and use the same artifacts when running against 1.5.0. It appears that the biggest blocker to this is the fact that the changes to the Catalyst `Expression` API in 1.5 appear to have broken compatibility for expressions implemented against the 1.4 API. 1.5 added new abstract methods without providing default implementations, leading to AbstractMethodErrors at runtime; it also modified the signatures of other methods, which will probably lead to NoSuchMethodErrors. I don't think that we can easily patch around this by adding compatibility layers / fallback code in a 1.5.2 release, either.

As it exists today, I don't think that `Expression` is a stable extension point for code which has to be compatible against major versions. For now, if this library needs to rely on custom `Expressions` then I think that we'll have to co-version it with Spark until we can produce a stable Expression API that's suitable for public consumption. Similar to the InternalRow/ExternalRow split, we might be able to define a set of ExternalExpression APIs which we can commit to as stable extension points if we want to enable this type of code to live outside of Spark in a stable fashion. This may be a fairly large design task, though. Let's continue to chat about this.

**Comment by harsha2010** [comment]
Hi Josh

Thanks for investigating this.. It is absolutely necessary that expression APIs be stable... I don't see how library designers can develop on top of Spark without such stable APIs. My hope is that Spark soon stabilizes on this so we don't have to co-version for too long.
Let's chat more when I get back

Ram

**Comment by JoshRosen** [comment]
In the medium-term, I'd like to propose a stopgap solution to let us move forward with development on this package:

Let's minimize the use of Spark-internal APIs by defining thin shims that live under the `org.apache.spark.sql.compat` namespace, then re-write this library's classes to live under the `magellan` namespace and to depend only our compatibility shims. If we want to publish different releases for different Spark versions, then we can maintain two separate versions of these shims and have the SBT build switch between them based on the Spark version. The common interface exposed by these shims will basically serve as a stable Expression API from a source-compatibility point-of-view. This would give us the opportunity to figure out exactly which interfaces we'd need to stabilize.

From users' perspectives, code compiled against Magellan would be source- and binary-compatible with different artifacts; the user would only need to ensure that the runtime Magellan dependency matches their Spark version.

/cc @marmbrus @pwendell

**Comment by harsha2010** [comment]
@JoshRosen this sounds good
