### ISSUE TITLE
Support for MultiPolygon

### ISSUE THREAD

**Issue by simonellistonball** [harsha2010/magellan#30]
Currently Multi-Polygons are not supported in the GeoJSON reader. 

Would it make sense to implement this by breaking down into multiple polygon records, or better to add a first-class MultiPolygon to the output schema?

**Comment by harsha2010** [comment]
@simonellistonball , great question .. We should be able to support this as array of polygon type instead of polygon... I think serialization should be handled automatically for us efficiently and I don't see any reason right now for multipolygon to be anything more than an array of polygons
Can you give it a try and see if it will work?

**Comment by Perados** [comment]
👍

**Comment by halfabrane** [comment]
done! #123
