### ISSUE TITLE
Upgrade Magellan to Spark 2.x

### ISSUE THREAD

**Issue by harsha2010** [harsha2010/magellan#82]

**Comment by jameyhicks** [comment]
How much work is required to support Spark 2.x?

**Comment by michaeldchin** [comment]
@harsha2010 I noticed the recent commit #85 update for Spark 2.1.  

I am currently using the magellan 1.0.4 snapshot. I'm interested using it in production software in the near future. I'm wondering when we can expect a release or some info about the current state of 1.0.4. 

Are there are any major changes in the API or known compatibility issues with Spark 2.1. Also maybe some info on what needs to be implemented for 1.0.4 to be released?

Thanks

**Comment by waras2017** [comment]
@harsha2010
I am also interested in using magellan 1.0.4 in a production software in the near future.
Since the current release version 1.0.3-s_2.10 is not working with Spark 2.1.0 I am very interested in the release version for magellan 1.0.4. What are the next steps and the timeline to get this release version?
Thanks a lot for the great work!

**Comment by harsha2010** [comment]
done
