### ISSUE TITLE
Question: how joins are performed ?

### ISSUE THREAD

**Issue by mdespriee** [harsha2010/magellan#92]
Hello,

This lib is quite interesting, especially with your recent move to spark 2.1 : well done !

I would like to better understand how queries like this are internally performed: `points.join(polygons).where($"point" intersects $"polygon").show()`

From what I understand from you code, it's more or less a cartesian join + filter. Am I correct ?
This is not scalable to large datasets. Do you plan to implement optimization strategies, such as rtrees, or anything similar ?

**Comment by harsha2010** [comment]
good question.. yes, right now it is more or less cartesian join, the only optimization is that in the case the shape dataset is small enough, it triggers a broadcast nested loop join.
i am working on a spatial join optimization which i'll share more about in a separate PR, it uses spatial curve based indices instead of R Trees

**Comment by harsha2010** [comment]
@mdespriee  check this PR out. This adds spatial indices to Magellan. #95 
Do give it a try and give me feedback. I am still working on a spatial join that transparently uses indices but for now you can follow the PR and rewrite any cross join in Magellan to use spatial indices manually
